# Generated by Django 5.1.6 on 2025-02-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite_kg', models.PositiveIntegerField()),
                ('localisation', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Épuisée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offres_images/')),
                ('cree_a', models.DateTimeField(auto_now_add=True)),
                ('collecteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
