# Generated by Django 5.1.6 on 2025-02-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='type_offre',
            field=models.CharField(choices=[('vente', 'Vente'), ('don', 'Don')], default='vente', max_length=20),
        ),
    ]
