# Generated by Django 5.1.6 on 2025-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_offre_type_offre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offre',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.RenameField(
            model_name='offre',
            old_name='cree_a',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='offre',
            old_name='collecteur',
            new_name='producteur',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='prix_par_kg',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='quantite_kg',
        ),
        migrations.AddField(
            model_name='offre',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='prix_kg',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Prix en Ariary par kilogramme', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offres/'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archivee', 'Archivée')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='offre',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offre',
            name='type_offre',
            field=models.CharField(choices=[('legume', 'Légume'), ('fruit', 'Fruit'), ('viande', 'Viande'), ('poisson', 'Poisson'), ('autre', 'Autre')], default='legume', max_length=20),
        ),
    ]
