# Generated by Django 5.1.6 on 2025-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_offre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='type_offre',
            field=models.CharField(choices=[('vente', 'Vente'), ('don', 'Don')], default='vente', max_length=20),
        ),
    ]
