# Generated by Django 5.1.6 on 2025-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_blacklistedtoken_user_verification_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
