# Generated by Django 5.1.6 on 2025-02-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateurs_alter_user_numero_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
