# Generated by Django 5.1.6 on 2025-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('collecteur', 'Collecteur'), ('agent', 'Agent de réception')], default='client', max_length=20),
        ),
    ]
