# Generated by Django 5.1.6 on 2025-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_collecteur_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
