# Generated by Django 5.1.6 on 2025-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_user_is_collecteur_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('collecteur', 'Collecteur'), ('agent', 'Agent de réception'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
